import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai, Prompt } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/navbar/navbar";
import MainNavbar from "@/src/components/navbar/mainNavbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const prompt = Prompt({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const noto_thai = Noto_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body className={`${prompt.className}`}>
        {/* <Navbar /> */}
        <MainNavbar />
        <main className="pt-14">{children}</main>
      </body>
    </html>
  );
}
